# Example GraphQL schema showing how record schemas and records can be queried.
# """
# Ariadne code gen bug.... to support new stuff we need to patch it
# got to file->
# vi .venv/lib/python3.12/site-packages/ariadne_codegen/client_generators/result_types.py
#
# top file import:
# from graphql import GraphQLNonNull, GraphQLString  # at top of file
#
# replace:
# GraphQLNonNull(type_=GraphQLScalarType(name="String"))
#
# with:
# GraphQLNonNull(GraphQLString)
#
# """

fragment BoolFieldDefinition on BoolFieldGql {
    id
    label
    description
    defaultBool
}

fragment DateFieldDefinition on DateFieldGql {
    id
    label
    description
    defaultDate
}

fragment DateTimeFieldDefinition on DateTimeFieldGql {
    id
    label
    description
    defaultDatetime
}

fragment EmailFieldDefinition on EmailFieldGql {
    id
    label
    description
    defaultEmail
}

fragment EnumFieldDefinition on EnumFieldGql {
    id
    label
    description
    allowedValues
    defaultStr
}

fragment FloatFieldDefinition on FloatFieldGql {
    id
    label
    description
    defaultFloat
    constraintsFloat {
        geFloat
        leFloat
    }
}

fragment IntFieldDefinition on IntFieldGql {
    id
    label
    description
    defaultInt
    constraintsInt {
        geInt
        leInt
    }
}

fragment JsonFieldDefinition on JsonFieldGql {
    id
    label
    description
    defaultDict
}

fragment ListFieldDefinition on ListFieldGql {
    id
    label
    description
    defaultList
}

fragment StrFieldDefinition on StrFieldGql {
    id
    label
    description
    defaultStr
    constraintsStr {
        minLength
        maxLength
    }
}

fragment UuidFieldDefinition on UuidFieldGql {
    id
    label
    description
    defaultUuid
}

fragment ObjectFieldDefinition on ObjectFieldGql {
    id
    label
    description
    #fields {
    #  __typename
    #  ...BoolFieldDefinition
    #  ...DateFieldDefinition
    #  ...DateTimeFieldDefinition
    #  ...EmailFieldDefinition
    #  ...EnumFieldDefinition
    #  ...FloatFieldDefinition
    #  ...IntFieldDefinition
    #  ...JsonFieldDefinition
    #  ...ListFieldDefinition
    #  ...StrFieldDefinition
    #  ...UuidFieldDefinition
    #  # Nested object fields repeat the same fragment spreads if required.
    #}
}


query queryRecordSchema($recordSchemaId: UUID!){
    recordSchema(recordSchemaId: $recordSchemaId) {
        count
        schemas {
            id
            name
            description
            fieldDefinitions {
                ...BoolFieldDefinition
                ...DateFieldDefinition
                ...DateTimeFieldDefinition
                ...EmailFieldDefinition
                ...EnumFieldDefinition
                ...FloatFieldDefinition
                ...IntFieldDefinition
                ...JsonFieldDefinition
                ...ListFieldDefinition
                ...StrFieldDefinition
                ...UuidFieldDefinition
                ...ObjectFieldDefinition
            }
        }
    }
}

query queryRecords($recordSchemaId: UUID!){
    records(recordSchemaId: $recordSchemaId){
        count
        records
    }
}

mutation mutateRecordSchema($schemaToAdd: JSON!){
    recordSchema(schemaToAdd: $schemaToAdd) {
        count
        schemas {
            id
            name
            description
            fieldDefinitions {
                ...BoolFieldDefinition
                ...DateFieldDefinition
                ...DateTimeFieldDefinition
                ...EmailFieldDefinition
                ...EnumFieldDefinition
                ...FloatFieldDefinition
                ...IntFieldDefinition
                ...JsonFieldDefinition
                ...ListFieldDefinition
                ...StrFieldDefinition
                ...UuidFieldDefinition
                ...ObjectFieldDefinition
            }
        }
    }
}

mutation mutateRecords($recordSchemaId: UUID!, $records: JSON!){
    records(recordSchemaId: $recordSchemaId, records: $records){
        count
        records
    }
}
