# Generated by ariadne-codegen
# Source: example

from typing import Any

from .base_model import BaseModel


class MutateRecords(BaseModel):
    records: "MutateRecordsRecords"


class MutateRecordsRecords(BaseModel):
    count: int
    records: Any


MutateRecords.model_rebuild()
