# Generated by ariadne-codegen
# Source: example

from typing import Annotated, Any, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import (
    BoolFieldDefinition,
    DateFieldDefinition,
    DateTimeFieldDefinition,
    EmailFieldDefinition,
    EnumFieldDefinition,
    FloatFieldDefinition,
    IntFieldDefinition,
    JsonFieldDefinition,
    ListFieldDefinition,
    ObjectFieldDefinition,
    StrFieldDefinition,
    UuidFieldDefinition,
)


class MutateRecordSchema(BaseModel):
    record_schema: "MutateRecordSchemaRecordSchema" = Field(alias="recordSchema")


class MutateRecordSchemaRecordSchema(BaseModel):
    count: int
    schemas: List["MutateRecordSchemaRecordSchemaSchemas"]


class MutateRecordSchemaRecordSchemaSchemas(BaseModel):
    id: Any
    name: str
    description: Optional[str]
    field_definitions: Optional[
        List[
            Annotated[
                Union[
                    "MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsBoolFieldGql",
                    "MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsDateFieldGql",
                    "MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsDateTimeFieldGql",
                    "MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsEmailFieldGql",
                    "MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsEnumFieldGql",
                    "MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsFloatFieldGql",
                    "MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsIntFieldGql",
                    "MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsJsonFieldGql",
                    "MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsListFieldGql",
                    "MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsStrFieldGql",
                    "MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsUuidFieldGql",
                    "MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsObjectFieldGql",
                ],
                Field(discriminator="typename__"),
            ]
        ]
    ] = Field(alias="fieldDefinitions")


class MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsBoolFieldGql(BoolFieldDefinition):
    typename__: Literal["BoolFieldGql"] = Field(alias="__typename")


class MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsDateFieldGql(DateFieldDefinition):
    typename__: Literal["DateFieldGql"] = Field(alias="__typename")


class MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsDateTimeFieldGql(DateTimeFieldDefinition):
    typename__: Literal["DateTimeFieldGql"] = Field(alias="__typename")


class MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsEmailFieldGql(EmailFieldDefinition):
    typename__: Literal["EmailFieldGql"] = Field(alias="__typename")


class MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsEnumFieldGql(EnumFieldDefinition):
    typename__: Literal["EnumFieldGql"] = Field(alias="__typename")


class MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsFloatFieldGql(FloatFieldDefinition):
    typename__: Literal["FloatFieldGql"] = Field(alias="__typename")


class MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsIntFieldGql(IntFieldDefinition):
    typename__: Literal["IntFieldGql"] = Field(alias="__typename")


class MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsJsonFieldGql(JsonFieldDefinition):
    typename__: Literal["JsonFieldGql"] = Field(alias="__typename")


class MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsListFieldGql(ListFieldDefinition):
    typename__: Literal["ListFieldGql"] = Field(alias="__typename")


class MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsStrFieldGql(StrFieldDefinition):
    typename__: Literal["StrFieldGql"] = Field(alias="__typename")


class MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsUuidFieldGql(UuidFieldDefinition):
    typename__: Literal["UuidFieldGql"] = Field(alias="__typename")


class MutateRecordSchemaRecordSchemaSchemasFieldDefinitionsObjectFieldGql(ObjectFieldDefinition):
    typename__: Literal["ObjectFieldGql"] = Field(alias="__typename")


MutateRecordSchema.model_rebuild()
MutateRecordSchemaRecordSchema.model_rebuild()
MutateRecordSchemaRecordSchemaSchemas.model_rebuild()
