# Generated by ariadne-codegen
# Source: example

from datetime import datetime
from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class BoolFieldDefinition(BaseModel):
    id: str
    label: str
    description: Optional[str]
    default_bool: Optional[bool] = Field(alias="defaultBool")


class DateFieldDefinition(BaseModel):
    id: str
    label: str
    description: Optional[str]
    default_date: Optional[Any] = Field(alias="defaultDate")


class DateTimeFieldDefinition(BaseModel):
    id: str
    label: str
    description: Optional[str]
    default_datetime: Optional[datetime] = Field(alias="defaultDatetime")


class EmailFieldDefinition(BaseModel):
    id: str
    label: str
    description: Optional[str]
    default_email: Optional[str] = Field(alias="defaultEmail")


class EnumFieldDefinition(BaseModel):
    id: str
    label: str
    description: Optional[str]
    allowed_values: Optional[List[str]] = Field(alias="allowedValues")
    default_str: Optional[str] = Field(alias="defaultStr")


class FloatFieldDefinition(BaseModel):
    id: str
    label: str
    description: Optional[str]
    default_float: Optional[float] = Field(alias="defaultFloat")
    ge_float: Optional[float] = Field(alias="geFloat")
    le_float: Optional[float] = Field(alias="leFloat")


class IntFieldDefinition(BaseModel):
    id: str
    label: str
    description: Optional[str]
    default_int: Optional[int] = Field(alias="defaultInt")
    ge_int: Optional[int] = Field(alias="geInt")
    le_int: Optional[int] = Field(alias="leInt")


class JsonFieldDefinition(BaseModel):
    id: str
    label: str
    description: Optional[str]
    default_dict: Any = Field(alias="defaultDict")


class ListFieldDefinition(BaseModel):
    id: str
    label: str
    description: Optional[str]
    default_list: Any = Field(alias="defaultList")


class ObjectFieldDefinition(BaseModel):
    id: str
    label: str
    description: Optional[str]


class StrFieldDefinition(BaseModel):
    id: str
    label: str
    description: Optional[str]
    default_str: Optional[str] = Field(alias="defaultStr")
    min_length: Optional[int] = Field(alias="minLength")
    max_length: Optional[int] = Field(alias="maxLength")


class UuidFieldDefinition(BaseModel):
    id: str
    label: str
    description: Optional[str]
    default_uuid: Optional[Any] = Field(alias="defaultUuid")


BoolFieldDefinition.model_rebuild()
DateFieldDefinition.model_rebuild()
DateTimeFieldDefinition.model_rebuild()
EmailFieldDefinition.model_rebuild()
EnumFieldDefinition.model_rebuild()
FloatFieldDefinition.model_rebuild()
IntFieldDefinition.model_rebuild()
JsonFieldDefinition.model_rebuild()
ListFieldDefinition.model_rebuild()
ObjectFieldDefinition.model_rebuild()
StrFieldDefinition.model_rebuild()
UuidFieldDefinition.model_rebuild()
