# Generated by ariadne-codegen
# Source: example

from typing import Any

from .base_model import BaseModel


class QueryRecords(BaseModel):
    records: "QueryRecordsRecords"


class QueryRecordsRecords(BaseModel):
    count: int
    records: Any


QueryRecords.model_rebuild()
