# Generated by ariadne-codegen
# Source: example

from typing import Annotated, List, Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import (
    BoolFieldDefinition,
    DateFieldDefinition,
    DateTimeFieldDefinition,
    EmailFieldDefinition,
    EnumFieldDefinition,
    FloatFieldDefinition,
    IntFieldDefinition,
    JsonFieldDefinition,
    ListFieldDefinition,
    ObjectFieldDefinition,
    StrFieldDefinition,
    UuidFieldDefinition,
)


class RecordFields(BaseModel):
    typed_fields: "RecordFieldsTypedFields" = Field(alias="typedFields")


class RecordFieldsTypedFields(BaseModel):
    fields: List[
        Annotated[
            Union[
                "RecordFieldsTypedFieldsFieldsBoolFieldGql",
                "RecordFieldsTypedFieldsFieldsDateFieldGql",
                "RecordFieldsTypedFieldsFieldsDateTimeFieldGql",
                "RecordFieldsTypedFieldsFieldsEmailFieldGql",
                "RecordFieldsTypedFieldsFieldsEnumFieldGql",
                "RecordFieldsTypedFieldsFieldsFloatFieldGql",
                "RecordFieldsTypedFieldsFieldsIntFieldGql",
                "RecordFieldsTypedFieldsFieldsJsonFieldGql",
                "RecordFieldsTypedFieldsFieldsListFieldGql",
                "RecordFieldsTypedFieldsFieldsStrFieldGql",
                "RecordFieldsTypedFieldsFieldsUuidFieldGql",
                "RecordFieldsTypedFieldsFieldsObjectFieldGql",
            ],
            Field(discriminator="typename__"),
        ]
    ]


class RecordFieldsTypedFieldsFieldsBoolFieldGql(BoolFieldDefinition):
    typename__: Literal["BoolFieldGql"] = Field(alias="__typename")


class RecordFieldsTypedFieldsFieldsDateFieldGql(DateFieldDefinition):
    typename__: Literal["DateFieldGql"] = Field(alias="__typename")


class RecordFieldsTypedFieldsFieldsDateTimeFieldGql(DateTimeFieldDefinition):
    typename__: Literal["DateTimeFieldGql"] = Field(alias="__typename")


class RecordFieldsTypedFieldsFieldsEmailFieldGql(EmailFieldDefinition):
    typename__: Literal["EmailFieldGql"] = Field(alias="__typename")


class RecordFieldsTypedFieldsFieldsEnumFieldGql(EnumFieldDefinition):
    typename__: Literal["EnumFieldGql"] = Field(alias="__typename")


class RecordFieldsTypedFieldsFieldsFloatFieldGql(FloatFieldDefinition):
    typename__: Literal["FloatFieldGql"] = Field(alias="__typename")


class RecordFieldsTypedFieldsFieldsIntFieldGql(IntFieldDefinition):
    typename__: Literal["IntFieldGql"] = Field(alias="__typename")


class RecordFieldsTypedFieldsFieldsJsonFieldGql(JsonFieldDefinition):
    typename__: Literal["JsonFieldGql"] = Field(alias="__typename")


class RecordFieldsTypedFieldsFieldsListFieldGql(ListFieldDefinition):
    typename__: Literal["ListFieldGql"] = Field(alias="__typename")


class RecordFieldsTypedFieldsFieldsStrFieldGql(StrFieldDefinition):
    typename__: Literal["StrFieldGql"] = Field(alias="__typename")


class RecordFieldsTypedFieldsFieldsUuidFieldGql(UuidFieldDefinition):
    typename__: Literal["UuidFieldGql"] = Field(alias="__typename")


class RecordFieldsTypedFieldsFieldsObjectFieldGql(ObjectFieldDefinition):
    typename__: Literal["ObjectFieldGql"] = Field(alias="__typename")


RecordFields.model_rebuild()
RecordFieldsTypedFields.model_rebuild()
